"""add server api key in provider

Revision ID: 039b8beb949a
Revises: c5a622978c81
Create Date: 2026-04-02 13:54:47.830981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039b8beb949a'
down_revision: Union[str, Sequence[str], None] = 'c5a622978c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('encoded_server_auth_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'encoded_server_auth_key')
    # ### end Alembic commands ###
