"""added gift table

Revision ID: 24f94ba4ada1
Revises: 55750969a92d
Create Date: 2025-11-28 09:38:33.653907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f94ba4ada1'
down_revision: Union[str, Sequence[str], None] = '55750969a92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gift_code', sa.String(length=50), nullable=False),
    sa.Column('purchaser_email', sa.String(length=255), nullable=False),
    sa.Column('purchaser_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='giftsubscriptionstatus'), nullable=False),
    sa.Column('gift_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_checkout_session_id')
    )
    op.create_index(op.f('ix_gift_subscriptions_gift_code'), 'gift_subscriptions', ['gift_code'], unique=True)
    op.create_index(op.f('ix_gift_subscriptions_id'), 'gift_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_gift_subscriptions_recipient_email'), 'gift_subscriptions', ['recipient_email'], unique=False)
    op.add_column('users', sa.Column('active_gift_subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'gift_subscriptions', ['active_gift_subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_gift_subscription_id')
    op.drop_index(op.f('ix_gift_subscriptions_recipient_email'), table_name='gift_subscriptions')
    op.drop_index(op.f('ix_gift_subscriptions_id'), table_name='gift_subscriptions')
    op.drop_index(op.f('ix_gift_subscriptions_gift_code'), table_name='gift_subscriptions')
    op.drop_table('gift_subscriptions')
    # ### end Alembic commands ###
