"""add build_versions table

Revision ID: 2929d39a7b36
Revises: bcef08cb58c3
Create Date: 2026-06-29 14:06:43.356628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2929d39a7b36'
down_revision: Union[str, Sequence[str], None] = 'bcef08cb58c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_versions_id'), 'build_versions', ['id'], unique=False)
    op.create_index(op.f('ix_build_versions_platform'), 'build_versions', ['platform'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_versions_platform'), table_name='build_versions')
    op.drop_index(op.f('ix_build_versions_id'), table_name='build_versions')
    op.drop_table('build_versions')
    # ### end Alembic commands ###
