"""add is generating llm to provider

Revision ID: 2e5969b2947e
Revises: b4c1c99a82d4
Create Date: 2026-04-12 00:49:51.076920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e5969b2947e"
down_revision: Union[str, Sequence[str], None] = "b4c1c99a82d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column(
            "is_generating_llm", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "providers",
        sa.Column("llm_jobs_done", sa.Integer(), nullable=True, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("providers", "llm_jobs_done")
    op.drop_column("providers", "is_generating_llm")
    # ### end Alembic commands ###
