"""add provider daily stats table

Revision ID: 31f39f0a9895
Revises: 039b8beb949a
Create Date: 2026-04-02 20:25:08.892388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f39f0a9895'
down_revision: Union[str, Sequence[str], None] = '039b8beb949a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_presence_minutes', sa.Float(), nullable=True),
    sa.Column('is_eligible_for_payout', sa.Boolean(), nullable=True),
    sa.Column('avg_similarity_score', sa.Float(), nullable=True),
    sa.Column('total_verifications', sa.Integer(), nullable=True),
    sa.Column('successful_verifications', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'date', name='_provider_date_uc')
    )
    op.create_index(op.f('ix_provider_daily_stats_date'), 'provider_daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_provider_daily_stats_id'), 'provider_daily_stats', ['id'], unique=False)
    op.create_index(op.f('ix_provider_daily_stats_provider_id'), 'provider_daily_stats', ['provider_id'], unique=False)
    op.add_column('providers', sa.Column('is_online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'is_online')
    op.drop_index(op.f('ix_provider_daily_stats_provider_id'), table_name='provider_daily_stats')
    op.drop_index(op.f('ix_provider_daily_stats_id'), table_name='provider_daily_stats')
    op.drop_index(op.f('ix_provider_daily_stats_date'), table_name='provider_daily_stats')
    op.drop_table('provider_daily_stats')
    # ### end Alembic commands ###
