"""removed sha256 row from build version

Revision ID: 45439336accc
Revises: 2929d39a7b36
Create Date: 2026-06-29 14:16:49.769647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45439336accc'
down_revision: Union[str, Sequence[str], None] = '2929d39a7b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_versions', 'sha256')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build_versions', sa.Column('sha256', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
