"""add key retrieved at

Revision ID: 7269b8cd6d96
Revises: 45439336accc
Create Date: 2026-07-13 07:57:44.962475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7269b8cd6d96'
down_revision: Union[str, Sequence[str], None] = '45439336accc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('key_retrieved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'key_retrieved_at')
    # ### end Alembic commands ###
