"""add verify duration

Revision ID: 7a8bf174f316
Revises: 53a24b186e5c
Create Date: 2026-04-03 18:08:10.042983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8bf174f316'
down_revision: Union[str, Sequence[str], None] = '53a24b186e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_samples', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_samples', 'duration')
    # ### end Alembic commands ###
