"""add provider tables

Revision ID: 9ab473590767
Revises: ed2ce5d1862a
Create Date: 2026-03-29 17:42:40.198708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab473590767'
down_revision: Union[str, Sequence[str], None] = 'ed2ce5d1862a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('email_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='emaillogstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_status_created', 'email_logs', ['status', 'created_at'], unique=False)
    op.create_index('idx_email_type_status', 'email_logs', ['email_type', 'status'], unique=False)
    op.create_index(op.f('ix_email_logs_created_at'), 'email_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_logs_email_type'), 'email_logs', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_recipient_email'), 'email_logs', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_logs_status'), 'email_logs', ['status'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('ban_reason', sa.String(length=500), nullable=True),
    sa.Column('jobs_done', sa.Integer(), nullable=True),
    sa.Column('jobs_failed', sa.Integer(), nullable=True),
    sa.Column('billable_jobs', sa.Integer(), nullable=True),
    sa.Column('uptime_score', sa.Float(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verification_failures', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_user_id'), 'providers', ['user_id'], unique=False)
    op.create_table('provider_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_job_status', 'provider_jobs', ['provider_id', 'status'], unique=False)
    op.create_index('idx_provider_job_user', 'provider_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_provider_jobs_id'), 'provider_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_provider_jobs_user_id'), 'provider_jobs', ['user_id'], unique=False)
    op.create_table('provider_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('pinged_at', sa.DateTime(), nullable=False),
    sa.Column('responded', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ping_provider_date', 'provider_pings', ['provider_id', 'pinged_at'], unique=False)
    op.create_index(op.f('ix_provider_pings_id'), 'provider_pings', ['id'], unique=False)
    op.create_index(op.f('ix_provider_pings_provider_id'), 'provider_pings', ['provider_id'], unique=False)
    op.create_table('provider_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=255), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_verifications_id'), 'provider_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_provider_verifications_provider_id'), 'provider_verifications', ['provider_id'], unique=False)
    op.add_column('users', sa.Column('unsubscribe_token', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('public_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_id')
    op.drop_column('users', 'unsubscribe_token')
    op.drop_index(op.f('ix_provider_verifications_provider_id'), table_name='provider_verifications')
    op.drop_index(op.f('ix_provider_verifications_id'), table_name='provider_verifications')
    op.drop_table('provider_verifications')
    op.drop_index(op.f('ix_provider_pings_provider_id'), table_name='provider_pings')
    op.drop_index(op.f('ix_provider_pings_id'), table_name='provider_pings')
    op.drop_index('idx_ping_provider_date', table_name='provider_pings')
    op.drop_table('provider_pings')
    op.drop_index(op.f('ix_provider_jobs_user_id'), table_name='provider_jobs')
    op.drop_index(op.f('ix_provider_jobs_id'), table_name='provider_jobs')
    op.drop_index('idx_provider_job_user', table_name='provider_jobs')
    op.drop_index('idx_provider_job_status', table_name='provider_jobs')
    op.drop_table('provider_jobs')
    op.drop_index(op.f('ix_providers_user_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_status'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_recipient_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_email_type'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_created_at'), table_name='email_logs')
    op.drop_index('idx_email_type_status', table_name='email_logs')
    op.drop_index('idx_email_status_created', table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
