"""add activation key

Revision ID: b4c1c99a82d4
Revises: 7a8bf174f316
Create Date: 2026-04-04 16:39:24.040824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4c1c99a82d4"
down_revision: Union[str, Sequence[str], None] = "7a8bf174f316"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers", sa.Column("activation_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "providers",
        sa.Column(
            "activation_token_used",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    op.add_column(
        "providers",
        sa.Column("activation_token_expires_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "providers", sa.Column("encoded_api_key", sa.String(length=500), nullable=True)
    )
    op.create_unique_constraint(None, "providers", ["activation_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "providers", type_="unique")
    op.drop_column("providers", "encoded_api_key")
    op.drop_column("providers", "activation_token_expires_at")
    op.drop_column("providers", "activation_token_used")
    op.drop_column("providers", "activation_token")
    # ### end Alembic commands ###
