"""add provider_semantic_warnings table

Revision ID: bc0242a1cba4
Revises: 2e5969b2947e
Create Date: 2026-04-12 01:12:54.359632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0242a1cba4'
down_revision: Union[str, Sequence[str], None] = '2e5969b2947e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_semantic_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('llm_response', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_semantic_warnings_provider_id'), 'provider_semantic_warnings', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_semantic_warnings_provider_id'), table_name='provider_semantic_warnings')
    op.drop_table('provider_semantic_warnings')
    # ### end Alembic commands ###
