"""add license tables

Revision ID: bcef08cb58c3
Revises: bc0242a1cba4
Create Date: 2026-06-19 15:56:54.466882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcef08cb58c3'
down_revision: Union[str, Sequence[str], None] = 'bc0242a1cba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('max_activations', sa.Integer(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_checkout_session_id')
    )
    op.create_index(op.f('ix_licenses_email'), 'licenses', ['email'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_user_id'), 'licenses', ['user_id'], unique=False)
    op.create_table('license_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_id', 'machine_id', name='_license_machine_uc')
    )
    op.create_index('idx_activation_license_machine', 'license_activations', ['license_id', 'machine_id'], unique=False)
    op.create_index(op.f('ix_license_activations_id'), 'license_activations', ['id'], unique=False)
    op.create_index(op.f('ix_license_activations_license_id'), 'license_activations', ['license_id'], unique=False)
    op.create_index(op.f('ix_license_activations_machine_id'), 'license_activations', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_activations_machine_id'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_license_id'), table_name='license_activations')
    op.drop_index(op.f('ix_license_activations_id'), table_name='license_activations')
    op.drop_index('idx_activation_license_machine', table_name='license_activations')
    op.drop_table('license_activations')
    op.drop_index(op.f('ix_licenses_user_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_email'), table_name='licenses')
    op.drop_table('licenses')
    # ### end Alembic commands ###
