"""add financereport table

Revision ID: c5a622978c81
Revises: dc312368cbf1
Create Date: 2026-03-30 09:09:22.095533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a622978c81'
down_revision: Union[str, Sequence[str], None] = 'dc312368cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_revenue_eur', sa.Float(), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('platform_fee_eur', sa.Float(), nullable=False),
    sa.Column('distributable_eur', sa.Float(), nullable=False),
    sa.Column('eligible_providers', sa.Integer(), nullable=False),
    sa.Column('share_per_provider_eur', sa.Float(), nullable=False),
    sa.Column('remainder_eur', sa.Float(), nullable=False),
    sa.Column('transfers', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_reports_id'), 'finance_reports', ['id'], unique=False)
    op.create_index(op.f('ix_finance_reports_month'), 'finance_reports', ['month'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_reports_month'), table_name='finance_reports')
    op.drop_index(op.f('ix_finance_reports_id'), table_name='finance_reports')
    op.drop_table('finance_reports')
    # ### end Alembic commands ###
