"""add accept_news_updates to users

Revision ID: ca4bbe376697
Revises: ee5fc0aa7c5c
Create Date: 2025-10-24 21:59:22.837876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4bbe376697'
down_revision: Union[str, Sequence[str], None] = 'ee5fc0aa7c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accept_news_updates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accept_news_updates')
    # ### end Alembic commands ###
