"""add ownershiplog table

Revision ID: dc312368cbf1
Revises: 9ab473590767
Create Date: 2026-03-30 08:48:59.141769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc312368cbf1'
down_revision: Union[str, Sequence[str], None] = '9ab473590767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_hash', sa.String(length=8), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('audio_content_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ownership_user_date', 'ownership_logs', ['public_user_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_ownership_logs_generated_at'), 'ownership_logs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ownership_logs_id'), 'ownership_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ownership_logs_public_user_id'), 'ownership_logs', ['public_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ownership_logs_public_user_id'), table_name='ownership_logs')
    op.drop_index(op.f('ix_ownership_logs_id'), table_name='ownership_logs')
    op.drop_index(op.f('ix_ownership_logs_generated_at'), table_name='ownership_logs')
    op.drop_index('idx_ownership_user_date', table_name='ownership_logs')
    op.drop_table('ownership_logs')
    # ### end Alembic commands ###
