"""added last_credit_refill_at in gift sub

Revision ID: f5d709d3788a
Revises: a44aec592fbd
Create Date: 2025-11-28 17:55:28.190360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d709d3788a'
down_revision: Union[str, Sequence[str], None] = 'a44aec592fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_subscriptions', sa.Column('last_credit_refill_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_subscriptions', 'last_credit_refill_at')
    # ### end Alembic commands ###
